### ISSUE TITLE
今天又更新了

### ISSUE THREAD

**Issue by githaoyang** [hidacow/SHU-Selfreport-Shortcuts#1]
之前用了好久，感觉非常好用，感谢分享，但是从今天开始需要上传健康吗。好像只要传两张照片上去就行，能不能更新一下，每次从图库中读取两张图，然后自动上传。

**Comment by hidacow** [comment]
由于通过快捷指令发送上传图片请求需要以文本方式发送图片文件内容
经研究，快捷指令在将文件原始数据转化为文本时编码会发生变化造成上传的图片文件损坏
目前未找到有效的方法，故上传本地图片功能暂时不考虑添加
不过通过刚刚更新中的`获取已上传图片id`快捷指令，你可以方便地获取自行上传图片的id并将其应用导入到接下来的每日一报中，便可实现自定义每天上报的图片

**Comment by hidacow** [comment]
由于图片上传功能似乎仅在返校时生效，需求较小，不考虑改进该功能。

This issue will be closed.
