### ISSUE TITLE
默认填写“不在校”影响核酸检测

### ISSUE THREAD

**Issue by olivier4934** [hidacow/SHU-Selfreport-Shortcuts#2]
请教一下怎么修改参数 默认填写“不在校”影响核酸检测预约
![C3A4D0FE-83AF-4862-97B3-3DDB2A9AC2C9](https://user-images.githubusercontent.com/62902725/160760690-2c0d7261-784f-4787-bde5-44ccf7a1b5f0.png)
![EC5DF16C-28A4-4D1F-82D5-5F13F865B4A9](https://user-images.githubusercontent.com/62902725/160760702-e69999d2-4c45-41a9-b5f6-8ee85f9cc87f.png)

**Comment by hidacow** [comment]
抱歉给您带来不便，在更新脚本时我也发现了选择不在校问题，由于本人技术水平有限，经过尝试修改一些参数仍旧无法定位和解决该问题，由于本人时间较为有限，最近无法投入更多时间调查该问题，若您发现了脚本中参数的设置问题，可以在此处反馈或者提交PR
暂时的解决方法是在需要核酸检测或预约当天在健康之路中选择每日一报手动选择在校，校区，其余日期可以自动填报，据观察不会影响在校状态和核酸检测预约状态。

**Comment by olivier4934** [comment]
> 

感谢回复 实际上对于使用没有带来特别大的影响 感谢您的无私贡献 我也一直在尝试制作脚本但奈何水平有限 一直也没找到入手方向 想请教一下iOS捷径入门有什么课程推荐么

**Comment by hidacow** [comment]
可能这方面的专门课程较少，个人认为快捷指令中的功能也较为局限，仅能够完成一些并不复杂的程序。一般来说，若学习了其它编程语言，使用快捷指令也能触类旁通。您可以通过查看快捷指令中心中的各示例指令，查看操作列表，阅读相关文档等了解其编写特点。若需要编写涉及网络的脚本，您可能还需要了解爬虫相关知识，此类网上有较多教程。

**Comment by hidacow** [comment]
Closed due to inactivity.

**Comment by hidacow** [comment]
Fixed in the latest version.
