### ISSUE TITLE
需要上传行程码就会填报失败。

### ISSUE THREAD

**Issue by lijinwill** [hidacow/SHU-Selfreport-Shortcuts#3]
请教老哥这个问题如何解决，不需要上传行程码可以填报成功，需要上传就会填报失败。
那个获取到的行程码id的快捷指令有什么用呢？

**Comment by hidacow** [comment]
这是一个已知问题，获取图片id快捷指令现阶段可能无效
最近健康之路系统对填报时行程码参数进行了校验
原先仅需提交图片id系统即认为已上传过
现在经尝试，系统似乎仅许可**当日上传**且**本人上传**的图片id参数，否则提示异常
因此，本脚本现有模式下似乎没有办法成功，必须先提交图片并获取其id后才能进行填报
如果有更好的想法或有绕过的方法可以提交PR或在这里讨论

**Comment by lijinwill** [comment]
可以考虑做一个，一键截取行程码的快捷指令，然后将截取到的行程码加入到原先的填报快捷指令里面。

**Comment by hidacow** [comment]
在最新的版本中已修复
目前默认提交无效图片，如确有需要可以尝试修改上传图片快捷指令，并提交正常的图片内容
但本人之前的尝试中发现使快捷指令提交正确的文件内容较为困难，近期未试验过
